run('battery_ws.m');
run('contactor_ws.m');
run('charger_ws.m');
run('drivetrain_ws.m');
run('battery_LUT.m');
run('fault_parameters.m');

Simulink.defineIntEnumType('SystemState_t', ... 
	{'Parking', 'Driving', 'Charging', 'Balancing'}, ...
	[0;1;2;3], ... 
	'Description', 'General System State enum typedef', ...
	'DefaultValue', 'Parking', ...
	'DataScope', 'Exported', ...
	'AddClassNameToEnumNames', true, ...
	'StorageType', 'int16');

load('bus_definitions.mat');

DeltaVTargetMin = 0.001;
balancingTime = 2000;
balancingRelaxationTime = 1000;
